import '../models/unit.dart';
import 'package:realm_of_tactics/models/unit_stats.dart';

final Map<String, Unit> unitData = {
  'Icewall Sentinel': Unit(
    id: 'template_Icewall Sentinel',
    unitName: 'Icewall Sentinel',
    unitClass: 'Defender',
    synergies: ['Defender', 'Tank', 'Frostward'],
    cost: 1,
    tier: 1,
    abilityName: "Frost Barrier",
    stats: UnitStats(
      baseMaxHealth: 650,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.6,
      baseArmor: 40,
      baseMagicResist: 30,
      baseRange: 1,
      baseMaxMana: 100,
      baseStartingMana: 50,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Defender', 'Tank'],
    origins: ['Frostward'],
    imagePath: 'assets/images/units/icewall_sentinel.png',
  ),
  'Winterblade Guardian': Unit(
    id: 'template_Winterblade Guardian',
    unitName: 'Winterblade Guardian',
    unitClass: 'Knight',
    synergies: ['Knight', 'Frostward'],
    cost: 1,
    tier: 1,
    abilityName: "Freezing Slash",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 70,
      baseAttackSpeed: 0.65,
      baseArmor: 35,
      baseMagicResist: 25,
      baseRange: 1,
      baseMaxMana: 70,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Knight'],
    origins: ['Frostward'],
    imagePath: 'assets/images/units/winterblade_guardian.png',
  ),
  'Glacier Marksman': Unit(
    id: 'template_Glacier Marksman',
    unitName: 'Glacier Marksman',
    unitClass: 'Rifleman',
    synergies: ['Rifleman', 'Frostward'],
    cost: 2,
    tier: 1,
    abilityName: "Frigid Volley",
    stats: UnitStats(
      baseMaxHealth: 500,
      baseAttackDamage: 70,
      baseAttackSpeed: 0.75,
      baseArmor: 20,
      baseMagicResist: 20,
      baseRange: 4,
      baseMaxMana: 120,
      baseStartingMana: 75,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Rifleman'],
    origins: ['Frostward'],
    imagePath: 'assets/images/units/glacier_marksman.png',
  ),
  'Rimebound Vanguard': Unit(
    id: 'template_Rimebound Vanguard',
    unitName: 'Rimebound Vanguard',
    unitClass: 'Tank',
    synergies: ['Tank', 'Frostward'],
    cost: 2,
    tier: 1,
    abilityName: "Glacial Aegis",
    stats: UnitStats(
      baseMaxHealth: 750,
      baseAttackDamage: 55,
      baseAttackSpeed: 0.6,
      baseArmor: 45,
      baseMagicResist: 40,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 40,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Tank'],
    origins: ['Frostward'],
    imagePath: 'assets/images/units/rimebound_vanguard.png',
  ),
  'Snowfall Priest': Unit(
    id: 'template_Snowfall Priest',
    unitName: 'Snowfall Priest',
    unitClass: 'Cleric',
    synergies: ['Cleric', 'Battlemage', 'Frostward'],
    cost: 3,
    tier: 1,
    abilityName: "Blessed Renewal",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 30,
      baseAttackSpeed: 0.7,
      baseArmor: 30,
      baseMagicResist: 30,
      baseRange: 3,
      baseMaxMana: 90,
      baseStartingMana: 35,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Cleric', 'Battlemage'],
    origins: ['Frostward'],
    imagePath: 'assets/images/units/snowfall_priest.png',
  ),
  'Northwind Tracker': Unit(
    id: 'template_Northwind Tracker',
    unitName: 'Northwind Tracker',
    unitClass: 'Scout',
    synergies: ['Scout', 'Frostward'],
    cost: 3,
    tier: 1,
    abilityName: "Crippling Dagger",
    stats: UnitStats(
      baseMaxHealth: 580,
      baseAttackDamage: 70,
      baseAttackSpeed: 0.75,
      baseArmor: 30,
      baseMagicResist: 25,
      baseRange: 2,
      baseMaxMana: 60,
      baseStartingMana: 25,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Scout'],
    origins: ['Frostward'],
    imagePath: 'assets/images/units/northwind_tracker.png',
  ),
  'Borealis Arcanist': Unit(
    id: 'template_Borealis Arcanist',
    unitName: 'Borealis Arcanist',
    unitClass: 'Battlemage',
    synergies: ['Battlemage', 'Frostward'],
    cost: 4,
    tier: 1,
    abilityName: "Starfall Convergence",
    stats: UnitStats(
      baseMaxHealth: 650,
      baseAttackDamage: 35,
      baseAttackSpeed: 0.7,
      baseArmor: 25,
      baseMagicResist: 45,
      baseRange: 3,
      baseMaxMana: 100,
      baseStartingMana: 50,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Battlemage'],
    origins: ['Frostward'],
    imagePath: 'assets/images/units/borealis_arcanist.png',
  ),
  'Frostscribe Mystic': Unit(
    id: 'template_Frostscribe Mystic',
    unitName: 'Frostscribe Mystic',
    unitClass: 'Runesmith',
    synergies: ['Runesmith', 'Frostward'],
    cost: 4,
    tier: 1,
    abilityName: 'Runic Protection',
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 35,
      baseAttackSpeed: 0.65,
      baseArmor: 30,
      baseMagicResist: 50,
      baseRange: 2,
      baseMaxMana: 80,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Runesmith'],
    origins: ['Frostward'],
    imagePath: 'assets/images/units/frostscribe_mystic.png',
  ),

  'Thunder Caller': Unit(
    id: 'template_Thunder Caller',
    unitName: 'Thunder Caller',
    unitClass: 'Battlemage',
    synergies: ['Battlemage', 'Stormpeak'],
    cost: 1,
    tier: 1,
    abilityName: "Thunder Strike",
    stats: UnitStats(
      baseMaxHealth: 550,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.7,
      baseArmor: 20,
      baseMagicResist: 35,
      baseRange: 3,
      baseMaxMana: 80,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Battlemage'],
    origins: ['Stormpeak'],
    imagePath: 'assets/images/units/thunder_caller.png',
  ),
  'Cloudbreaker': Unit(
    id: 'template_Cloudbreaker',
    unitName: 'Cloudbreaker',
    unitClass: 'Knight',
    synergies: ['Knight', 'Stormpeak'],
    cost: 1,
    tier: 1,
    abilityName: "Thundering Might",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 65,
      baseAttackSpeed: 0.65,
      baseArmor: 35,
      baseMagicResist: 25,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 40,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Knight'],
    origins: ['Stormpeak'],
    imagePath: 'assets/images/units/cloudbreaker.png',
  ),
  'Stormcarver': Unit(
    id: 'template_Stormcarver',
    unitName: 'Stormcarver',
    unitClass: 'Runesmith',
    synergies: ['Runesmith', 'Stormpeak'],
    cost: 2,
    tier: 1,
    abilityName: "Runic Empowerment",
    stats: UnitStats(
      baseMaxHealth: 580,
      baseAttackDamage: 55,
      baseAttackSpeed: 0.7,
      baseArmor: 25,
      baseMagicResist: 40,
      baseRange: 1,
      baseMaxMana: 100,
      baseStartingMana: 60,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Runesmith'],
    origins: ['Stormpeak'],
    imagePath: 'assets/images/units/stormcarver.png',
  ),
  'Highrock Bulwark': Unit(
    id: 'template_Highrock Bulwark',
    unitName: 'Highrock Bulwark',
    unitClass: 'Defender',
    synergies: ['Defender', 'Stormpeak'],
    cost: 3,
    tier: 1,
    abilityName: 'Stoneguard Stance',
    stats: UnitStats(
      baseMaxHealth: 700,
      baseAttackDamage: 50,
      baseAttackSpeed: 0.6,
      baseArmor: 50,
      baseMagicResist: 40,
      baseRange: 1,
      baseMaxMana: 125,
      baseStartingMana: 70,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Defender'],
    origins: ['Stormpeak'],
    imagePath: 'assets/images/units/highrock_bulwark.png',
  ),
  'Skyfire Sharpshooter': Unit(
    id: 'template_Skyfire Sharpshooter',
    unitName: 'Skyfire Sharpshooter',
    unitClass: 'Rifleman',
    synergies: ['Rifleman', 'Stormpeak'],
    cost: 3,
    tier: 1,
    abilityName: 'Deadeye Barrage',
    stats: UnitStats(
      baseMaxHealth: 550,
      baseAttackDamage: 75,
      baseAttackSpeed: 0.8,
      baseArmor: 20,
      baseMagicResist: 25,
      baseRange: 4,
      baseMaxMana: 120,
      baseStartingMana: 50,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Rifleman'],
    origins: ['Stormpeak'],
    imagePath: 'assets/images/units/skyfire_sharpshooter.png',
  ),
  'Tempest Cannoneer': Unit(
    id: 'template_Tempest Cannoneer',
    unitName: 'Tempest Cannoneer',
    unitClass: 'Artillerist',
    synergies: ['Artillerist', 'Stormpeak'],
    cost: 4,
    tier: 1,
    abilityName: 'Cannon Blast',
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 85,
      baseAttackSpeed: 0.7,
      baseArmor: 25,
      baseMagicResist: 25,
      baseRange: 3,
      baseMaxMana: 90,
      baseStartingMana: 35,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Artillerist'],
    origins: ['Stormpeak'],
    imagePath: 'assets/images/units/tempest_cannoneer.png',
  ),
  'Stormlord': Unit(
    id: 'template_Stormlord',
    unitName: 'Stormlord',
    unitClass: 'Knight',
    synergies: ['Knight', 'Stormpeak'],
    cost: 5,
    tier: 1,
    abilityName: "Hurricane's Eye",
    stats: UnitStats(
      baseMaxHealth: 900,
      baseAttackDamage: 90,
      baseAttackSpeed: 0.7,
      baseArmor: 50,
      baseMagicResist: 45,
      baseRange: 1,
      baseMaxMana: 100,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Knight'],
    origins: ['Stormpeak'],
    imagePath: 'assets/images/units/stormlord.png',
  ),

  'Emberforger': Unit(
    id: 'template_Emberforger',
    unitName: 'Emberforger',
    unitClass: 'Runesmith',
    synergies: ['Runesmith', 'Forgeheart'],
    cost: 3,
    tier: 1,
    abilityName: "Molten Tempo",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.7,
      baseArmor: 30,
      baseMagicResist: 40,
      baseRange: 3,
      baseMaxMana: 75,
      baseStartingMana: 0,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Runesmith'],
    origins: ['Forgeheart'],
    imagePath: 'assets/images/units/emberforger.png',
  ),
  'Flamespeaker': Unit(
    id: 'template_Flamespeaker',
    unitName: 'Flamespeaker',
    unitClass: 'Battlemage',
    synergies: ['Battlemage', 'Forgeheart'],
    cost: 4,
    tier: 1,
    abilityName: 'Flare Nova',
    stats: UnitStats(
      baseMaxHealth: 650,
      baseAttackDamage: 75,
      baseAttackSpeed: 0.7,
      baseArmor: 30,
      baseMagicResist: 45,
      baseRange: 3,
      baseMaxMana: 70,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Battlemage'],
    origins: ['Forgeheart'],
    imagePath: 'assets/images/units/flamespeaker.png',
  ),
  'Cinderblade': Unit(
    id: 'template_Cinderblade',
    unitName: 'Cinderblade',
    unitClass: 'Spellblade',
    synergies: ['Spellblade', 'Forgeheart'],
    cost: 5,
    tier: 1,
    abilityName: 'Ignited Slash',
    stats: UnitStats(
      baseMaxHealth: 750,
      baseAttackDamage: 95,
      baseAttackSpeed: 0.8,
      baseArmor: 35,
      baseMagicResist: 35,
      baseRange: 1,
      baseMaxMana: 60,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Spellblade'],
    origins: ['Forgeheart'],
    imagePath: 'assets/images/units/cinderblade.png',
  ),

  'Granite Guard': Unit(
    id: 'template_Granite Guard',
    unitName: 'Granite Guard',
    unitClass: 'Defender',
    synergies: ['Defender', 'Stoneborn'],
    cost: 1,
    tier: 1,
    abilityName: 'Stoneform',
    stats: UnitStats(
      baseMaxHealth: 700,
      baseAttackDamage: 50,
      baseAttackSpeed: 0.6,
      baseArmor: 45,
      baseMagicResist: 30,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 40,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Defender'],
    origins: ['Stoneborn'],
    imagePath: 'assets/images/units/granite_guard.png',
  ),
  'Stonebinder': Unit(
    id: 'template_Stonebinder',
    unitName: 'Stonebinder',
    unitClass: 'Cleric',
    synergies: ['Cleric', 'Stoneborn'],
    cost: 2,
    tier: 1,
    abilityName: 'Stonebond Ritual',
    stats: UnitStats(
      baseMaxHealth: 550,
      baseAttackDamage: 45,
      baseAttackSpeed: 0.65,
      baseArmor: 25,
      baseMagicResist: 40,
      baseRange: 3,
      baseMaxMana: 80,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Cleric'],
    origins: ['Stoneborn'],
    imagePath: 'assets/images/units/stonebinder.png',
  ),
  'Colossus Rider': Unit(
    id: 'template_Colossus Rider',
    unitName: 'Colossus Rider',
    unitClass: 'Beast Rider',
    synergies: ['Beast Rider', 'Stoneborn'],
    cost: 4,
    tier: 1,
    abilityName: 'Colossal Might',
    stats: UnitStats(
      baseMaxHealth: 800,
      baseAttackDamage: 70,
      baseAttackSpeed: 0.75,
      baseArmor: 40,
      baseMagicResist: 30,
      baseRange: 1,
      baseMaxMana: 90,
      baseStartingMana: 0,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Beast Rider'],
    origins: ['Stoneborn'],
    imagePath: 'assets/images/units/colossus_rider.png',
  ),
  'Earthshaper': Unit(
    id: 'template_Earthshaper',
    unitName: 'Earthshaper',
    unitClass: 'Tank',
    synergies: ['Tank', 'Stoneborn'],
    cost: 5,
    tier: 1,
    abilityName: 'Seismic Bulwark',
    stats: UnitStats(
      baseMaxHealth: 1100,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.6,
      baseArmor: 60,
      baseMagicResist: 50,
      baseRange: 1,
      baseMaxMana: 120,
      baseStartingMana: 70,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Tank'],
    origins: ['Stoneborn'],
    imagePath: 'assets/images/units/earthshaper.png',
  ),

  'Cogsmith': Unit(
    id: 'template_Cogsmith',
    unitName: 'Cogsmith',
    unitClass: 'Engineer',
    synergies: ['Engineer', 'Ironvale'],
    cost: 1,
    tier: 1,
    abilityName: "Deploy Gearbot",
    stats: UnitStats(
      baseMaxHealth: 550,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.7,
      baseArmor: 25,
      baseMagicResist: 25,
      baseRange: 2,
      baseMaxMana: 80,
      baseStartingMana: 40,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Engineer'],
    origins: ['Ironvale'],
    imagePath: 'assets/images/units/cogsmith.png',
  ),
  'Gearcaster': Unit(
    id: 'template_Gearcaster',
    unitName: 'Gearcaster',
    unitClass: 'Battlemage',
    synergies: ['Battlemage', 'Defender', 'Ironvale'],
    cost: 2,
    tier: 1,
    abilityName: "Aegis Pulse",
    stats: UnitStats(
      baseMaxHealth: 650,
      baseAttackDamage: 40,
      baseAttackSpeed: 0.65,
      baseArmor: 40,
      baseMagicResist: 40,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 40,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Battlemage', 'Defender'],
    origins: ['Ironvale'],
    imagePath: 'assets/images/units/gearcaster.png',
  ),
  'Ironclad': Unit(
    id: 'template_Ironclad',
    unitName: 'Ironclad',
    unitClass: 'Tank',
    synergies: ['Tank', 'Ironvale'],
    cost: 2,
    tier: 1,
    abilityName: "Fortress Slam",
    stats: UnitStats(
      baseMaxHealth: 700,
      baseAttackDamage: 55,
      baseAttackSpeed: 0.6,
      baseArmor: 45,
      baseMagicResist: 35,
      baseRange: 1,
      baseMaxMana: 50,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Tank'],
    origins: ['Ironvale'],
    imagePath: 'assets/images/units/ironclad.png',
  ),
  'Spark Duelist': Unit(
    id: 'template_Spark Duelist',
    unitName: 'Spark Duelist',
    unitClass: 'Spellblade',
    synergies: ['Spellblade', 'Ironvale'],
    cost: 3,
    tier: 1,
    abilityName: "Twin Surge",
    stats: UnitStats(
      baseMaxHealth: 620,
      baseAttackDamage: 70,
      baseAttackSpeed: 0.8,
      baseArmor: 30,
      baseMagicResist: 30,
      baseRange: 1,
      baseMaxMana: 70,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Spellblade'],
    origins: ['Ironvale'],
    imagePath: 'assets/images/units/spark_duelist.png',
  ),
  'Clockwork Medic': Unit(
    id: 'template_Clockwork Medic',
    unitName: 'Clockwork Medic',
    unitClass: 'Cleric',
    synergies: ['Cleric', 'Ironvale'],
    cost: 4,
    tier: 1,
    abilityName: "Priority Pulse",
    stats: UnitStats(
      baseMaxHealth: 650,
      baseAttackDamage: 50,
      baseAttackSpeed: 0.7,
      baseArmor: 30,
      baseMagicResist: 45,
      baseRange: 3,
      baseMaxMana: 70,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Cleric'],
    origins: ['Ironvale'],
    imagePath: 'assets/images/units/clockwork_medic.png',
  ),
  'Mechwright': Unit(
    id: 'template_Mechwright',
    unitName: 'Mechwright',
    unitClass: 'Engineer',
    synergies: ['Engineer', 'Ironvale'],
    cost: 5,
    tier: 1,
    abilityName: 'Deploy Turret',
    stats: UnitStats(
      baseMaxHealth: 850,
      baseAttackDamage: 75,
      baseAttackSpeed: 0.75,
      baseArmor: 40,
      baseMagicResist: 40,
      baseRange: 3,
      baseMaxMana: 100,
      baseStartingMana: 50,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Engineer'],
    origins: ['Ironvale'],
    imagePath: 'assets/images/units/mechwright.png',
  ),

  'Timecarver': Unit(
    id: 'template_Timecarver',
    unitName: 'Timecarver',
    unitClass: 'Runesmith',
    synergies: ['Runesmith', 'Chronospark'],
    cost: 1,
    tier: 1,
    abilityName: "Temporal Inscription",
    stats: UnitStats(
      baseMaxHealth: 550,
      baseAttackDamage: 55,
      baseAttackSpeed: 0.7,
      baseArmor: 25,
      baseMagicResist: 35,
      baseRange: 2,
      baseMaxMana: 60,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Runesmith'],
    origins: ['Chronospark'],
    imagePath: 'assets/images/units/timecarver.png',
  ),
  'Gearstep Agent': Unit(
    id: 'template_Gearstep Agent',
    unitName: 'Gearstep Agent',
    unitClass: 'Scout',
    synergies: ['Scout', 'Chronospark'],
    cost: 2,
    tier: 1,
    abilityName: "Whirring Daggers",
    stats: UnitStats(
      baseMaxHealth: 580,
      baseAttackDamage: 65,
      baseAttackSpeed: 0.8,
      baseArmor: 25,
      baseMagicResist: 25,
      baseRange: 1,
      baseMaxMana: 60,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Scout'],
    origins: ['Chronospark'],
    imagePath: 'assets/images/units/gearstep_agent.png',
  ),
  'Clockmaker': Unit(
    id: 'template_Clockmaker',
    unitName: 'Clockmaker',
    unitClass: 'Engineer',
    synergies: ['Engineer', 'Chronospark'],
    cost: 3,
    tier: 1,
    abilityName: "Clockbot Construct",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.7,
      baseArmor: 30,
      baseMagicResist: 30,
      baseRange: 3,
      baseMaxMana: 50,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Engineer'],
    origins: ['Chronospark'],
    imagePath: 'assets/images/units/clockmaker.png',
  ),
  'Chrono Sniper': Unit(
    id: 'template_Chrono Sniper',
    unitName: 'Chrono Sniper',
    unitClass: 'Rifleman',
    synergies: ['Rifleman', 'Chronospark'],
    cost: 4,
    tier: 1,
    abilityName: "Piercing Round",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 80,
      baseAttackSpeed: 0.8,
      baseArmor: 25,
      baseMagicResist: 25,
      baseRange: 4,
      baseMaxMana: 100,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Rifleman'],
    origins: ['Chronospark'],
    imagePath: 'assets/images/units/chrono_sniper.png',
  ),
  'Epoch Guardian': Unit(
    id: 'template_Epoch Guardian',
    unitName: 'Epoch Guardian',
    unitClass: 'Tank',
    synergies: ['Tank', 'Chronospark'],
    cost: 4,
    tier: 1,
    abilityName: "Temporal Bulwark",
    stats: UnitStats(
      baseMaxHealth: 800,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.6,
      baseArmor: 50,
      baseMagicResist: 40,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Tank'],
    origins: ['Chronospark'],
    imagePath: 'assets/images/units/epoch_guardian.png',
  ),

  'Fieldrunner': Unit(
    id: 'template_Fieldrunner',
    unitName: 'Fieldrunner',
    unitClass: 'Scout',
    synergies: ['Scout', 'Greendale'],
    cost: 1,
    tier: 1,
    abilityName: "Precision Stab",
    stats: UnitStats(
      baseMaxHealth: 550,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.85,
      baseArmor: 25,
      baseMagicResist: 25,
      baseRange: 1,
      baseMaxMana: 60,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Scout'],
    origins: ['Greendale'],
    imagePath: 'assets/images/units/fieldrunner.png',
  ),
  'Seedtinker': Unit(
    id: 'template_Seedtinker',
    unitName: 'Seedtinker',
    unitClass: 'Engineer',
    synergies: ['Engineer', 'Greendale'],
    cost: 1,
    tier: 1,
    abilityName: "Veggiebot Swarm",
    stats: UnitStats(
      baseMaxHealth: 550,
      baseAttackDamage: 55,
      baseAttackSpeed: 0.7,
      baseArmor: 25,
      baseMagicResist: 25,
      baseRange: 2,
      baseMaxMana: 60,
      baseStartingMana: 50,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Engineer'],
    origins: ['Greendale'],
    imagePath: 'assets/images/units/seedtinker.png',
  ),
  'Harvest Warden': Unit(
    id: 'template_Harvest Warden',
    unitName: 'Harvest Warden',
    unitClass: 'Defender',
    synergies: ['Defender', 'Greendale'],
    cost: 2,
    tier: 1,
    abilityName: "Nature's Balance",
    stats: UnitStats(
      baseMaxHealth: 650,
      baseAttackDamage: 55,
      baseAttackSpeed: 0.65,
      baseArmor: 40,
      baseMagicResist: 30,
      baseRange: 1,
      baseMaxMana: 70,
      baseStartingMana: 0,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Defender'],
    origins: ['Greendale'],
    imagePath: 'assets/images/units/harvest_warden.png',
  ),

  'Spring Sage': Unit(
    id: 'template_Spring Sage',
    unitName: 'Spring Sage',
    unitClass: 'Cleric',
    synergies: ['Cleric', 'Greendale'],
    cost: 3,
    tier: 1,
    abilityName: "Rejuvenating Bloom",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 45,
      baseAttackSpeed: 0.65,
      baseArmor: 25,
      baseMagicResist: 40,
      baseRange: 3,
      baseMaxMana: 70,
      baseStartingMana: 25,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Cleric'],
    origins: ['Greendale'],
    imagePath: 'assets/images/units/spring_sage.png',
  ),
  'Farmland Protector': Unit(
    id: 'template_Farmland Protector',
    unitName: 'Farmland Protector',
    unitClass: 'Defender',
    synergies: ['Defender', 'Greendale'],
    cost: 4,
    tier: 1,
    abilityName: "Nature Guard",
    stats: UnitStats(
      baseMaxHealth: 850,
      baseAttackDamage: 65,
      baseAttackSpeed: 0.6,
      baseArmor: 55,
      baseMagicResist: 45,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Defender'],
    origins: ['Greendale'],
    imagePath: 'assets/images/units/farmland_protector.png',
  ),

  'Ashen Hunter': Unit(
    id: 'template_Ashen Hunter',
    unitName: 'Ashen Hunter',
    unitClass: 'Rifleman',
    synergies: ['Rifleman', 'Emberhill'],
    cost: 1,
    tier: 1,
    abilityName: "Flame Surge",
    stats: UnitStats(
      baseMaxHealth: 500,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.75,
      baseArmor: 20,
      baseMagicResist: 20,
      baseRange: 4,
      baseMaxMana: 100,
      baseStartingMana: 40,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Rifleman'],
    origins: ['Emberhill'],
    imagePath: 'assets/images/units/ashen_hunter.png',
  ),
  'Flare Charger': Unit(
    id: 'template_Flare Charger',
    unitName: 'Flare Charger',
    unitClass: 'Beast Rider',
    synergies: ['Beast Rider', 'Scout', 'Emberhill'],
    cost: 2,
    tier: 1,
    abilityName: "Flare Burst",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.75,
      baseArmor: 30,
      baseMagicResist: 30,
      baseRange: 1,
      baseMaxMana: 120,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Beast Rider', 'Scout'],
    origins: ['Emberhill'],
    imagePath: 'assets/images/units/flare_charger.png',
  ),
  'Firework Artisan': Unit(
    id: 'template_Firework Artisan',
    unitName: 'Firework Artisan',
    unitClass: 'Engineer',
    synergies: ['Engineer', 'Emberhill'],
    cost: 2,
    tier: 1,
    abilityName: "Firework Launch",
    stats: UnitStats(
      baseMaxHealth: 550,
      baseAttackDamage: 50,
      baseAttackSpeed: 0.7,
      baseArmor: 25,
      baseMagicResist: 30,
      baseRange: 3,
      baseMaxMana: 60,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Engineer'],
    origins: ['Emberhill'],
    imagePath: 'assets/images/units/firework_artisan.png',
  ),
  'Hearthguard': Unit(
    id: 'template_Hearthguard',
    unitName: 'Hearthguard',
    unitClass: 'Defender',
    synergies: ['Defender', 'Emberhill'],
    cost: 3,
    tier: 1,
    abilityName: "Scorching Bulwark",
    stats: UnitStats(
      baseMaxHealth: 750,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.6,
      baseArmor: 50,
      baseMagicResist: 40,
      baseRange: 1,
      baseMaxMana: 70,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Defender'],
    origins: ['Emberhill'],
    imagePath: 'assets/images/units/hearthguard.png',
  ),
  'Inferno Fencer': Unit(
    id: 'template_Inferno Fencer',
    unitName: 'Inferno Fencer',
    unitClass: 'Spellblade',
    synergies: ['Spellblade', 'Emberhill'],
    cost: 4,
    tier: 1,
    abilityName: "Burning Riposte",
    stats: UnitStats(
      baseMaxHealth: 700,
      baseAttackDamage: 80,
      baseAttackSpeed: 0.8,
      baseArmor: 35,
      baseMagicResist: 35,
      baseRange: 1,
      baseMaxMana: 70,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Spellblade'],
    origins: ['Emberhill'],
    imagePath: 'assets/images/units/inferno_fencer.png',
  ),
  'Blazestep Ranger': Unit(
    id: 'template_Blazestep Ranger',
    unitName: 'Blazestep Ranger',
    unitClass: 'Scout',
    synergies: ['Scout', 'Emberhill'],
    cost: 5,
    tier: 1,
    abilityName: "Infernal Volley",
    stats: UnitStats(
      baseMaxHealth: 800,
      baseAttackDamage: 90,
      baseAttackSpeed: 0.9,
      baseArmor: 30,
      baseMagicResist: 30,
      baseRange: 3,
      baseMaxMana: 120,
      baseStartingMana: 50,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.2,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Scout'],
    origins: ['Emberhill'],
    imagePath: 'assets/images/units/blazestep_ranger.png',
  ),

  'Cloudburst Gunner': Unit(
    id: 'template_Cloudburst Gunner',
    unitName: 'Cloudburst Gunner',
    unitClass: 'Artillerist',
    synergies: ['Artillerist', 'Skyguard'],
    cost: 1,
    tier: 1,
    abilityName: "Rocket Barrage",
    stats: UnitStats(
      baseMaxHealth: 500,
      baseAttackDamage: 55,
      baseAttackSpeed: 0.7,
      baseArmor: 20,
      baseMagicResist: 25,
      baseRange: 4,
      baseMaxMana: 30,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Artillerist'],
    origins: ['Skyguard'],
    imagePath: 'assets/images/units/cloudburst_gunner.png',
  ),
  'Zephyr Mage': Unit(
    id: 'template_Zephyr Mage',
    unitName: 'Zephyr Mage',
    unitClass: 'Battlemage',
    synergies: ['Battlemage', 'Skyguard'],
    cost: 3,
    tier: 1,
    abilityName: "Twin Tempest",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 50,
      baseAttackSpeed: 0.65,
      baseArmor: 25,
      baseMagicResist: 40,
      baseRange: 3,
      baseMaxMana: 70,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Battlemage'],
    origins: ['Skyguard'],
    imagePath: 'assets/images/units/zephyr_mage.png',
  ),
  'Windlance Champion': Unit(
    id: 'template_Windlance Champion',
    unitName: 'Windlance Champion',
    unitClass: 'Knight',
    synergies: ['Knight', 'Skyguard'],
    cost: 4,
    tier: 1,
    abilityName: "Lance Strike",
    stats: UnitStats(
      baseMaxHealth: 800,
      baseAttackDamage: 80,
      baseAttackSpeed: 0.7,
      baseArmor: 45,
      baseMagicResist: 35,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Knight'],
    origins: ['Skyguard'],
    imagePath: 'assets/images/units/windlance_champion.png',
  ),
  'Nimbus Rider': Unit(
    id: 'template_Nimbus Rider',
    unitName: 'Nimbus Rider',
    unitClass: 'Beast Rider',
    synergies: ['Beast Rider', 'Skyguard'],
    cost: 5,
    tier: 1,
    abilityName: "Skyfall Assault",
    stats: UnitStats(
      baseMaxHealth: 950,
      baseAttackDamage: 85,
      baseAttackSpeed: 0.75,
      baseArmor: 40,
      baseMagicResist: 40,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.2,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Beast Rider'],
    origins: ['Skyguard'],
    imagePath: 'assets/images/units/nimbus_rider.png',
  ),

  'Tunnel Rusher': Unit(
    id: 'template_Tunnel Rusher',
    unitName: 'Tunnel Rusher',
    unitClass: 'Beast Rider',
    synergies: ['Beast Rider', 'Deeprock'],
    cost: 1,
    tier: 1,
    abilityName: "Burrow Maul",
    stats: UnitStats(
      baseMaxHealth: 600,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.65,
      baseArmor: 30,
      baseMagicResist: 20,
      baseRange: 1,
      baseMaxMana: 60,
      baseStartingMana: 10,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.1,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Beast Rider'],
    origins: ['Deeprock'],
    imagePath: 'assets/images/units/tunnel_rusher.png',
  ),
  'Stoneweaver': Unit(
    id: 'template_Stoneweaver',
    unitName: 'Stoneweaver',
    unitClass: 'Runesmith',
    synergies: ['Runesmith', 'Deeprock'],
    cost: 2,
    tier: 1,
    abilityName: "Earthen Fortitude",
    stats: UnitStats(
      baseMaxHealth: 580,
      baseAttackDamage: 50,
      baseAttackSpeed: 0.7,
      baseArmor: 30,
      baseMagicResist: 35,
      baseRange: 1,
      baseMaxMana: 100,
      baseStartingMana: 50,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Runesmith'],
    origins: ['Deeprock'],
    imagePath: 'assets/images/units/stoneweaver.png',
  ),
  'Cavern Raider': Unit(
    id: 'template_Cavern Raider',
    unitName: 'Cavern Raider',
    unitClass: 'Beast Rider',
    synergies: ['Beast Rider', 'Deeprock'],
    cost: 3,
    tier: 1,
    abilityName: "Screech and Strike",
    stats: UnitStats(
      baseMaxHealth: 700,
      baseAttackDamage: 70,
      baseAttackSpeed: 0.7,
      baseArmor: 35,
      baseMagicResist: 25,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.1,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Beast Rider'],
    origins: ['Deeprock'],
    imagePath: 'assets/images/units/cavern_raider.png',
  ),
  'Depthcharge Bomber': Unit(
    id: 'template_Depthcharge Bomber',
    unitName: 'Depthcharge Bomber',
    unitClass: 'Artillerist',
    synergies: ['Artillerist', 'Deeprock'],
    cost: 5,
    tier: 1,
    abilityName: "Crack and Blast",
    stats: UnitStats(
      baseMaxHealth: 800,
      baseAttackDamage: 100,
      baseAttackSpeed: 0.7,
      baseArmor: 30,
      baseMagicResist: 30,
      baseRange: 4,
      baseMaxMana: 120,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Artillerist'],
    origins: ['Deeprock'],
    imagePath: 'assets/images/units/depthcharge_bomber.png',
  ),

  'Sigil Keeper': Unit(
    id: 'template_Sigil Keeper',
    unitName: 'Sigil Keeper',
    unitClass: 'Tank',
    synergies: ['Tank', 'Runebound'],
    cost: 1,
    tier: 1,
    abilityName: "Runebound Pulse",
    stats: UnitStats(
      baseMaxHealth: 650,
      baseAttackDamage: 50,
      baseAttackSpeed: 0.6,
      baseArmor: 40,
      baseMagicResist: 40,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Tank'],
    origins: ['Runebound'],
    imagePath: 'assets/images/units/sigil_keeper.png',
  ),
  'Glyph Bomber': Unit(
    id: 'template_Glyph Bomber',
    unitName: 'Glyph Bomber',
    unitClass: 'Artillerist',
    synergies: ['Artillerist', 'Runebound'],
    cost: 2,
    tier: 1,
    abilityName: "Arcane Payload",
    stats: UnitStats(
      baseMaxHealth: 550,
      baseAttackDamage: 60,
      baseAttackSpeed: 0.75,
      baseArmor: 20,
      baseMagicResist: 30,
      baseRange: 4,
      baseMaxMana: 40,
      baseStartingMana: 0,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Artillerist'],
    origins: ['Runebound'],
    imagePath: 'assets/images/units/glyph_bomber.png',
  ),
  'Oathsworn': Unit(
    id: 'template_Oathsworn',
    unitName: 'Oathsworn',
    unitClass: 'Knight',
    synergies: ['Knight', 'Runebound'],
    cost: 3,
    tier: 1,
    abilityName: "Pledge of Steel",
    stats: UnitStats(
      baseMaxHealth: 700,
      baseAttackDamage: 70,
      baseAttackSpeed: 0.65,
      baseArmor: 40,
      baseMagicResist: 35,
      baseRange: 1,
      baseMaxMana: 60,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Knight'],
    origins: ['Runebound'],
    imagePath: 'assets/images/units/oathsworn.png',
  ),
  'Rune Architect': Unit(
    id: 'template_Rune Architect',
    unitName: 'Rune Architect',
    unitClass: 'Engineer',
    synergies: ['Engineer', 'Runesmith', 'Runebound'],
    cost: 4,
    tier: 1,
    abilityName: "Runic Assembly",
    stats: UnitStats(
      baseMaxHealth: 700,
      baseAttackDamage: 50,
      baseAttackSpeed: 0.7,
      baseArmor: 35,
      baseMagicResist: 35,
      baseRange: 3,
      baseMaxMana: 100,
      baseStartingMana: 40,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Engineer', 'Runesmith'],
    origins: ['Runebound'],
    imagePath: 'assets/images/units/rune_architect.png',
  ),
  'Veilstrider': Unit(
    id: 'template_Veilstrider',
    unitName: 'Veilstrider',
    unitClass: 'Scout',
    synergies: ['Scout', 'Runebound'],
    cost: 4,
    tier: 1,
    abilityName: "Shadow Surge",
    stats: UnitStats(
      baseMaxHealth: 680,
      baseAttackDamage: 75,
      baseAttackSpeed: 0.85,
      baseArmor: 30,
      baseMagicResist: 35,
      baseRange: 1,
      baseMaxMana: 120,
      baseStartingMana: 50,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.1,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Scout'],
    origins: ['Runebound'],
    imagePath: 'assets/images/units/veilstrider.png',
  ),
  'Enigmancer': Unit(
    id: 'template_Enigmancer',
    unitName: 'Enigmancer',
    unitClass: 'Battlemage',
    synergies: ['Battlemage', 'Runebound'],
    cost: 5,
    tier: 1,
    abilityName: "Mystic Cascade",
    stats: UnitStats(
      baseMaxHealth: 850,
      baseAttackDamage: 70,
      baseAttackSpeed: 0.7,
      baseArmor: 35,
      baseMagicResist: 50,
      baseRange: 3,
      baseMaxMana: 150,
      baseStartingMana: 50,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Battlemage'],
    origins: ['Runebound'],
    imagePath: 'assets/images/units/enigmancer.png',
  ),

  'Mountainbreaker': Unit(
    id: 'template_Mountainbreaker',
    unitName: 'Mountainbreaker',
    unitClass: 'Knight',
    synergies: ['Knight', 'Spellblade', 'Ironhide'],
    cost: 2,
    tier: 1,
    abilityName: "Earthsplitter",
    stats: UnitStats(
      baseMaxHealth: 700,
      baseAttackDamage: 55,
      baseAttackSpeed: 0.7,
      baseArmor: 35,
      baseMagicResist: 35,
      baseRange: 1,
      baseMaxMana: 80,
      baseStartingMana: 30,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Knight', 'Spellblade'],
    origins: ['Ironhide'],
    imagePath: 'assets/images/units/mountainbreaker.png',
  ),
  'Titan Sentinel': Unit(
    id: 'template_Titan Sentinel',
    unitName: 'Titan Sentinel',
    unitClass: 'Tank',
    synergies: ['Tank', 'Ironhide'],
    cost: 3,
    tier: 1,
    abilityName: "Unbreakable Form",
    stats: UnitStats(
      baseMaxHealth: 800,
      baseAttackDamage: 55,
      baseAttackSpeed: 0.6,
      baseArmor: 55,
      baseMagicResist: 45,
      baseRange: 1,
      baseMaxMana: 50,
      baseStartingMana: 20,
      baseAbilityPower: 100,
      baseCritChance: 0.25,
      baseCritDamage: 1.5,
      baseLifesteal: 0,
      baseMovementSpeed: 1.0,
      baseDamageAmp: 1.0,
      baseOnAttackStats: OnAttackStats.empty,
    ),
    classes: ['Tank'],
    origins: ['Ironhide'],
    imagePath: 'assets/images/units/titan_sentinel.png',
  ),
};
